version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ember-cli
    versions:
    - 3.23.0
    - 3.24.0
  - dependency-name: ember-source
    versions:
    - 3.24.0
    - 3.24.1
  - dependency-name: mocha
    versions:
    - 8.2.1
  - dependency-name: release-it
    versions:
    - 14.2.2
  - dependency-name: ember-cli-babel
    versions:
    - 7.23.0
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.3.1
